[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.poetry]
name = "vollseg"

[tool.poetry.build]
script = "python -c 'import vollseg; print(vollseg.__version__)'"
