# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "10.4.3.dev0+g6bf30fd.d20230409"
__version_tuple__ = version_tuple = (10, 4, 3, "dev0", "g6bf30fd.d20230409")
