# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "30.5.12.dev0+gf015625.d20230609"
__version_tuple__ = version_tuple = (30, 5, 12, "dev0", "gf015625.d20230609")
