# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "10.0.1.dev0+gad298d2.d20230402"
__version_tuple__ = version_tuple = (10, 0, 1, "dev0", "gad298d2.d20230402")
