# -*- coding: utf-8 -*-
"""Copy of DenoiseandSegment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_BqPub0uwnlwjn9JcsmWyq4CDtEmYZTZ
"""





import os
import glob
import sys
import numpy as np
from tqdm import tqdm
from tifffile import imread, imwrite
from stardist.models import StarDist3D
from csbdeep.models import Config, CARE
from vollseg import SmartSeedPrediction3D
os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"
from pathlib import Path

ImageDir = '/home/sancere/Kepler/ClaudiaTracking/Mari/Data/Raw/'
Model_Dir = '/home/sancere/Kepler/ClaudiaTracking/Mari/Data/TrainedModels/'

SaveDir = ImageDir + 'Results/'

NoiseModelName = 'Marid3f48'
UNETModelName = 'UNETMariNucleiSeg'
StarModelName = 'MariNucleiSeg'
UnetModel = CARE(config = None, name = UNETModelName, basedir = Model_Dir)
StarModel = StarDist3D(config = None, name = StarModelName, basedir = Model_Dir)
NoiseModel = CARE(config=None, name=NoiseModelName, basedir=Model_Dir)

Raw_path = os.path.join(ImageDir, '*.tif')
filesRaw = glob.glob(Raw_path)
filesRaw.sort
min_size = 100
n_tiles = (8,16,16)

for fname in filesRaw:
     
     SmartSeedPrediction3D(SaveDir, fname, UnetModel, StarModel,NoiseModel, min_size = min_size,  n_tiles = n_tiles, UseProbability = True)

